# File: robot/movement/route_recorder.py

import logging
from typing import Optional

from config import settings
from robot.navigation.planner import RoutePlan
from mini.apis.api_action import MoveRobotDirection

# Setup logger for this module
logger = logging.getLogger(__name__)

# This maps a direction to its exact opposite for the return trip
OPPOSITE_DIRECTIONS = {
    MoveRobotDirection.FORWARD: MoveRobotDirection.BACKWARD,
    MoveRobotDirection.BACKWARD: MoveRobotDirection.FORWARD,
    MoveRobotDirection.LEFTWARD: MoveRobotDirection.RIGHTWARD,
    MoveRobotDirection.RIGHTWARD: MoveRobotDirection.LEFTWARD,
}

class RouteRecorder:
    """
    Records a completed route and calculates the inverse route
    for the robot to return to its starting point.
    """

    def __init__(self):
        # This simply stores the last executed route in memory.
        # For a more robust system, you could save this to a file
        # in the data/routes/ directory.
        self.last_route: Optional[RoutePlan] = None
        logger.info("RouteRecorder initialized.")

    def save_route_for_return(self, route: RoutePlan):
        """
        Call this *before* the robot starts moving to save the plan.
        
        Args:
            route: The route plan generated by the Planner.
        """
        logger.info(f"Saving route for return trip: {route}")
        self.last_route = route

    def get_return_route(self) -> Optional[RoutePlan]:
        """
        Calculates the reverse of the last saved route.
        
        Returns:
            A new RoutePlan, with all steps and directions inverted.
        """
        if not self.last_route:
            logger.warning("Cannot get return route: No route was saved.")
            return None

        return_route: RoutePlan = []
        
        # Go through the original route *in reverse*
        for (direction, steps) in reversed(self.last_route):
            # Find the opposite direction
            opposite = OPPOSITE_DIRECTIONS.get(direction)
            if opposite:
                return_route.append((opposite, steps))
            else:
                logger.warning(f"Unknown direction '{direction}' in route, skipping.")
        
        logger.info(f"Generated return route: {return_route}")
        # Clear the last route so it's not used twice
        self.last_route = None
        
        return return_route